### PR TITLE
Change page to read from <input type="file" element instead of fs.readSync()

### LINKED ISSUE #26: Deploy to a webpage?
Think it would be ok for me to change this so that it can be deployed as a web app? I would basically just change it to use an `<input type="file">` element instead of electron's readSync().

### PR DESCRIPTION
**Pull request by sixcorners**
This makes it so that this can be deployed as a web app. Fixes #26

Check it out: https://sqlite3-page-explorer.pages.dev/  
If you want I can pull that down if you want to host it somewhere.

Think it's a good change?

### CODE REVIEW

**Comment by siara-cc** [comment]
Excellent idea.. just wow!!  Does it cost anything to host that one? If so I would like to host it with github pages.

**Comment by sixcorners** [comment]
It does not. I used cloudflare pages because there is a build step and you can use it for commercial purposes and you can use cloudflare workers with it (though I don't yet have a commercial page or one that uses workers and it looks like there is a build step for github pages also) but if you set it up with github pages then that works too. I'll go ahead and pull down the cloudflare pages one.

**Comment by siara-cc** [comment]
Ok, thats great!  I was just asking about cost otherwise I have no issue if you would like to host it for any purpose. I will  create the github page soon. Thanks!!

**Comment by siara-cc** [comment]
I have created a Credits section in Readme. If you would like to make any change please feel free.

**Pull request merged**
